services:
  - type: web
    name: ansambl-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn services.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: worker
    name: ansambl-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
